services:
  - type: web
    name: AI Resume Analyzer
    env: node
    plan: starter
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    autoDeploy: true
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
